config/routes.rb
ActionController::Routing::Routes.draw do |map|

  #map.resources :announcements, :controller => 'admin/announcements', :path_prefix => 'admin', :name_prefix => 'admin_'
  map.resources :announcements, :member => { :confirm_destroy => :get }

  #map.resources :assignments, :controller => 'admin/assignments', :path_prefix => 'admin', :name_prefix => 'admin_', :member => { :confirm_destroy => :get  }
  map.resources :assignments, :collection => { :all => :get }, :member => { :confirm_destroy => :get  }

  #map.resources :exams, :controller => 'admin/exams', :path_prefix => 'admin', :name_prefix => 'admin_', :member => { :confirm_destroy => :get }
  map.resources :exams, :collection => { :all => :get }, :member => { :confirm_destroy => :get }

  #map.resources :field_trips, :controller => 'admin/field_trips', :path_prefix => 'admin', :name_prefix => 'admin_', :member => { :confirm_destroy => :get }
  map.resources :field_trips, :collection => { :all => :get }, :member => { :confirm_destroy => :get }

  map.resources :teachers, :controller => 'admin/teachers', :path_prefix => 'admin', :name_prefix => 'admin_', :collection => { :dashboard => :get, :thanks => :get, :plans => :get, :billing => :any, :paypal => :any, :plan => :any, :plan_paypal => :any, :cancel => :any, :canceled => :get }
  map.resources :teachers, :only => [:show, :new, :create], :member => { :signup => :get, :signup_update => :put }, :collection => { :plans => :get, :export_agenda => :get, :search => :get }
  
  map.resources :users, :member => { :settings => :get, :admin => :put, :from_rpx => :get, :demo_menu => :get }, :collection => { :login_validate => :get, :rpx_create => :post, :demo => :get }
  map.resource :session, :collection => { :rpx_token => :post }
  
  map.resources :assets, :path_prefix => 'admin', :member => { :confirm_destroy => :get }, :collection =>  { :limit => :get }
  
  #subscriptions
  #map.with_options(:conditions => {:subdomain => /.+/}) do |subdom|
    #subdom.root :controller => 'subscription_admin/subscriptions', :action => 'index'
    #subdom.with_options(:namespace => 'subscription_admin/', :name_prefix => 'admin_', :path_prefix => nil) do |admin|
      #admin.resources :subscriptions, :member => { :charge => :post }
      #admin.resources :accounts
      #admin.resources :subscription_plans, :as => 'plans'
      #admin.resources :subscription_discounts, :as => 'discounts'
      #admin.resources :subscription_affiliates, :as => 'affiliates'
    #end
  #end

  map.resource :rpx, :only => [:create, :new], :controller => 'rpx'

  #classroom groups and classrooms
  map.resources :classroom_groups, :controller => 'admin/classroom_groups', :path_prefix => 'admin', :name_prefix => 'admin_', :new => { :signup => :get, :signup_create => :post }, :member => { :confirm_destroy => :get, :move_up => :put, :move_down => :put }, :collection => { :sort => :put, :needs_active_term => :get } do |classroom_group|
    classroom_group.resources :classrooms, :controller => 'admin/classrooms', :member => { :confirm_destroy => :get, :move_up => :put, :move_down => :put }, :collection => { :sort => :put }
  end
  
  map.resources :classroom_groups, :only => [:index] do |classroom_group|
    classroom_group.resources :classrooms, :only => [:index, :show]
  end
  
  map.resources :messages, :except => [:edit, :update], :member => { :confirm_destroy => :get }, :conditions => { :subdomain => true } 

  map.resources :classrooms, :only => [:index]

  map.teacher_root '', :controller => 'teachers', :action => 'show', :conditions => { :subdomain => true } 
  
  map.teacher_about '/about', :controller => 'teachers', :action => 'show', :conditions => { :subdomain => true } 
  map.teacher_feed '/feed', :controller => 'teachers', :action => 'show', :format => 'xml', :conditions => { :subdomain => true } 
  map.teacher_settings '/settings', :controller => 'users', :action => 'settings', :conditions => { :subdomain => true }
  
  map.connect '/:year/:month/:day',
              :conditions => { :subdomain => true, :method => :get }, 
              :controller => 'teachers', 
              :action => 'show_date', 
              :requirements => { :year => /(20)\d\d/, :month => /[01]\d/, :day => /[0-3]\d/ }

  
  #map.resources :users
  map.resource  :session,  :member => { :rpx_token, :any }
  
  map.forgot_password '/forgot', :controller => 'sessions', :action => 'forgot'
  map.reset_password '/reset/:token', :controller => 'sessions', :action => 'reset'
  
  #map.signup '/signup', :controller => 'users', :action => 'new'
  map.signup '/signup', :controller => 'rpx', :action => 'new' #:controller => 'teachers', :action => 'plans'
  map.new_user '/signup/:plan', :controller => 'users', :action => 'new', :plan => nil

  map.login  '/login', :controller => 'sessions', :action => 'new'
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'    
  map.terms '/terms', :controller => 'home', :action => 'terms'
  map.students_and_parents '/students_and_parents', :controller => 'home', :action => 'students_and_parents'
  map.contact '/contact', :controller => 'home', :action => 'contact'
  map.about '/about', :controller => 'home', :action => 'about'
  map.demo '/demo', :controller => 'users', :action => 'demo'
  map.calendar_help '/add_to_calendar', :controller => 'help', :action => 'add_to_calendar'
  map.pricing '/pricing', :controller => 'home', :action => 'pricing'
  
  map.rpx_login_return '/login_return', :controller => 'rpx', :action => 'login_return'
  
  map.root :controller => 'home', :action => 'index'# :controller => "teachers", :action => "index"  
  map.root_js '.js', :controller => 'home', :action => 'index'
  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
end

app/models/field_trip.rb
class FieldTrip < ActiveRecord::Base
  include CheckTimestamps  
  include ValidationMessage
  has_and_belongs_to_many :classrooms
  validates_presence_of :classrooms, :message => "^At least one classroom must be selected"
  validates_presence_of :title
  default_scope :order => 'field_trips.trip_date DESC'
  acts_as_polymorphic_paperclip
  include Assetable #needs to be last in - overrides after_save - poly paperclip does as well.
  
  def target_date
    trip_date
  end
end

app/controllers/admin/field_trips_controller.rb
class Admin::FieldTripsController < Admin::AdminController
  before_filter :load_field_trip, :only => [:show, :edit, :update, :destroy, :confirm_destroy]
  before_filter :needs_classroom, :only => [:index]
  
  def index
    @field_trips = logged_in_teacher.all_active_field_trips
  end

  def new
    @field_trip = FieldTrip.new
  end

  def create
    @field_trip = FieldTrip.new(params[:field_trip])

    if @field_trip.save
      flash[:notice] = 'Field Trip was successfully created.'
      redirect_to admin_field_trips_url
    else
      render :action => "new"
    end
  end

  def update
    if @field_trip.update_attributes(params[:field_trip])
      flash[:notice] = 'Field Trip was successfully updated.'
      redirect_to(admin_field_trips_url)
    else
      render :action => "edit"
    end
  end

  def destroy
    @field_trip.destroy

    respond_to do |format|
      format.html { redirect_to(admin_field_trips_url) }
      format.js  { render :nothing => true }
    end
  end
  
private
  def load_field_trip
    @field_trip = logged_in_teacher.all_active_field_trips.select { |e| e.id == params[:id].to_i }[0]
  end  
end

app/controllers/field_trips_controller.rb
class FieldTripsController < ApplicationController
  before_filter :current_teacher
  #before_filter :check_plan, :only => [:index, :show, :all]
  
  before_filter :load_teacher_field_trip, :only => [:edit, :update, :destroy, :confirm_destroy]
  before_filter :teacher_required, :except => [:show, :index, :all]  
  
  def index
    @field_trips = current_teacher.upcoming_field_trips

    respond_to do |format|
      format.html
      format.js { render :partial => 'index', :layout => "partial_with_title" }
    end
  end

  def show
    @field_trip = current_teacher.all_field_trips.select { |a| a.id == params[:id].to_i }[0]
    
    respond_to do |format|
      format.html
      format.js { render(:partial => 'show', :layout => 'details') }      
    end
  end
  
  def all
    @field_trips = current_teacher.all_active_field_trips
    
    respond_to do |format|
      format.html
      format.js { render :partial => 'all', :layout => "partial_with_title" }
    end
  end    
  
  def new
    @field_trip = FieldTrip.new
  end

  def create
    @field_trip = FieldTrip.new(params[:field_trip])

    if @field_trip.save
      flash[:notice] = 'Field Trip was successfully created.'
      redirect_to field_trips_url
    else
      render :action => "new"
    end
  end

  def update
    if @field_trip.update_attributes(params[:field_trip])
      flash[:notice] = 'Field Trip was successfully updated.'
      redirect_to(field_trips_url)
    else
      render :action => "edit"
    end
  end

  def destroy
    @field_trip.destroy

    respond_to do |format|
      format.html { redirect_to(field_trips_url) }
      format.js  { render :nothing => true }
    end
  end
  
private
  def load_teacher_field_trip
    @field_trip = logged_in_teacher.all_active_field_trips.select { |e| e.id == params[:id].to_i }[0]
  end    
end

app/helpers/field_trips_helper.rb
module FieldTripsHelper
  def field_trip_sentence(field_trip)
    sentence = "Field Trip <strong>#{h(field_trip.title)}</strong>"
    if field_trip.classrooms.length > 0 && field_trip.classrooms[0].classroom_group.has_multiple_classrooms?
      "#{sentence} for #{h(field_trip.classrooms.to_sentence)}."
    else
      "#{sentence}."
    end
  end
  
  def field_trip_updated_sentence(field_trip)
    action = field_trip.created_at == field_trip.updated_at ? "created" : "updated"
    sentence = sentence_icon("sx_icons_#{action}") + "<span class='sentence_indent'>Field Trip <strong>#{h(field_trip.title)}</strong> #{action}. Trip date is set for #{field_trip.trip_date}.</span>"
  end    
end

app/views/admin/field_trips/_form.html.erb
<% form_for([:admin, field_trip], :html => { :multipart => true }) do |f| %>
  <%= f.error_messages :header_message => field_trip.validation_header, :message => field_trip.validation_message %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :details %>
    <%= f.text_area :details %>
  </p>
  <p>
    <%= f.label :trip_date %>
    <%= render :partial => "partials/date_value", :locals => { :o => field_trip, :f => f, :date => field_trip.trip_date, :date_field => :trip_date } %>    
  </p>
  
  <h3>Which classrooms are going on this field trip?</h3>
  <% for classroom in logged_in_teacher.active_classrooms %>
  <label class="no_top_padding"><%= check_box_tag "field_trip[classroom_ids][]", classroom.id, field_trip.classrooms.include?(classroom) %> <%= classroom.name %></label>
  <% end %>  

  <h3>Attachments</h3>
  <%= render "assets/list", :assetable => field_trip, :admin => true %>

  <p>
    <%= f.label :data, "Attach a file or image", :class => "no_top_padding" %>
    <%= f.file_field :data %>
  </p>
  <p>
    <%= f.submit %> or <%= link_to 'Cancel', admin_field_trips_path %>
  </p>
<% end %>

app/views/admin/field_trips/_row.html.erb
<tr id="row_<%= field_trip.id %>" class="<%= cycle('odd', 'even')%>">
  <td><%=h field_trip.title %></td>
  <td><%=h field_trip.trip_date %></td>
  <td><%= link_to 'Edit', edit_admin_field_trip_path(field_trip), :title => "Edit field trip"  %></td>
  <td><%= link_to "Delete", confirm_destroy_admin_field_trip_path(field_trip), :class => "delete", :title => "Delete field trip" %></td>    
</tr>

app/views/admin/field_trips/confirm_destroy.html.erb
<% title "Delete Field Trip" %>

<% form_for [:admin, @field_trip], :html => { :method => :delete } do |f| %>
  <h2>Are you sure you want to delete this Field Trip?</h2>
  <p>
    <%= submit_tag "Delete" %> or <%= link_to "cancel", admin_field_trips_path %>
  </p>
<% end %>

app/views/admin/field_trips/edit.html.erb
<% title "Editing Field Trip" %>

<%= render :partial => "form", :locals => { :field_trip => @field_trip } %>

app/views/admin/field_trips/index.html.erb
<% title "Listing Field Trips" %>

<%- if @field_trips.empty? -%>
<br />
<p>Right now you don't have any Field Trips.</p>
<%- else -%>
<table id="field_trips_table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Trip date</th>
      <th colspan="2">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @field_trips.each do |field_trip| %>
      <%= render :partial => "row", :locals => { :field_trip => field_trip } %>
    <% end %>
  </tbody>
</table>
<%- end -%>

<br />

<%= link_to 'New Field Trip', new_admin_field_trip_path, :title => "New field trip" %> or <%= link_to "Back to Settings", settings_url %>

app/views/admin/field_trips/new.html.erb
<% title "New Field Trip" %>

<%= render :partial => "form", :locals => { :field_trip => @field_trip } %>

app/views/admin/field_trips/show.html.erb
<p>
  <b>Title:</b>
  <%=h @field_trip.title %>
</p>

<p>
  <b>Details:</b>
  <%=h @field_trip.details %>
</p>

<p>
  <b>Trip date:</b>
  <%=h @field_trip.trip_date %>
</p>


<%= link_to 'Edit', edit_admin_field_trip_path(@field_trip) %> |
<%= link_to 'Back', admin_field_trips_path %>